### ISSUE TITLE
learn Pull Request experiment

### ISSUE THREAD

**Issue by edmondsung** [processis/learnSpector#3]
为什么FIX 里的COMMENT，对方看不到

**Comment by shellyqinyu** [comment]
20230308 test

**Comment by edmondsung** [comment]
![coverDesign微信图片_20230301210027](https://user-images.githubusercontent.com/47587026/223602201-dadf4d92-ca82-4357-bcbf-5b91c0389b08.jpg)
附上截图，看到吗？

**Comment by shellyqinyu** [comment]
jietu

**Comment by edmondsung** [comment]
截图再试
![chess象棋WenkuBaidu](https://user-images.githubusercontent.com/47587026/223603375-5b3ca0d0-2295-40bf-8e8d-923f2aed50a7.jpg)

**Comment by shellyqinyu** [comment]
![Uploading figure 22.5.png…]()

**Comment by edmondsung** [comment]
Both can see images, sometime slow ..
